// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-m986v_ovY6bEAaiGoqBq3aVXBLAVkCM',
    appId: '1:1097056685313:android:51ba2e890ade3b70addf00',
    messagingSenderId: '1097056685313',
    projectId: 'linkedu-projeto-integrador',
    storageBucket: 'linkedu-projeto-integrador.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf-ZwOJwkTP2OeTm7St4xpqdzDLgpPN2w',
    appId: '1:1097056685313:ios:dadd69671a7861a3addf00',
    messagingSenderId: '1097056685313',
    projectId: 'linkedu-projeto-integrador',
    storageBucket: 'linkedu-projeto-integrador.appspot.com',
    iosBundleId: 'com.example.linkedu',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdC3cYE9qhohfHD25JLH5x8OCgESvbLnQ',
    appId: '1:1097056685313:web:3a8d77fcd45843c1addf00',
    messagingSenderId: '1097056685313',
    projectId: 'linkedu-projeto-integrador',
    authDomain: 'linkedu-projeto-integrador.firebaseapp.com',
    storageBucket: 'linkedu-projeto-integrador.appspot.com',
    measurementId: 'G-D357RLRE51',
  );

}